import './globals.css'
import Navbar from './Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='bg-lightGrey'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
